mostlyerror/swapp

- app/models/client.rb
- app/views/clients/_form.html.erb
- app/views/clients/_search_form.html.erb
- app/views/devise/sessions/new.html.erb
Finish building out all the questions that were present on @vagarioustoast's google form, and their corresponding values. Hardcoded values for the most part, for now. 
I have **not** built the form handlers. Will need to create a new client, along with an associated `intake` (model doesn't exist yet).
> Complete Intake Form

- app/views/layouts/_header.html.erb
swapp logo returns to home screen/client lookup
> makes logo return to home

- app/views/devise/sessions/new.html.erb
Enlarges remember me text and checkbox, adds a little top margin.
> makes remember me larger

- app/views/intakes/_form.html.erb
Increases margin, width, and height of each radio button in intake form according to Tailwind's preferred method. 
https://tailwindcss-custom-forms.netlify.app/
> Radio space

- app/views/intakes/_form.html.erb
- app/views/intakes/new.html.erb
* move voucher specific questions to bottom of form, possibly to its own form
* re-word ethnicity question
* help text/hint for email phone number
* help text/hint for optional email phone number
* switch client data section to single column new
> Intake Form Revision #3

- app/views/layouts/_footer.html.erb
adds footer content and a way to contact the team/provide feedback
> adds footer content

- app/controllers/vouchers_controller.rb
existing contact data right now, we should have multiple emails and
phones in the future)
> save phone number and email from voucher form to client record

- Gemfile
- Gemfile.lock
- app/controllers/clients_controller.rb
- app/controllers/intakes_controller.rb
- app/controllers/vouchers_controller.rb
- app/javascript/stylesheets/application.scss
- app/models/swap_intake.rb
- app/models/swap_period.rb
- app/models/voucher.rb
- app/views/admin/home/index.html.erb
- app/views/clients/_search_form.html.erb
- app/views/clients/index.html.erb
- app/views/clients/show.html.erb
- app/views/intakes/_form.html.erb
- app/views/swap_periods/index.html.erb
- app/views/vouchers/_form.html.erb
- config/application.rb
- db/migrate/20210220145617_change_vouchers_check_in_and_check_out_date_types.rb
- db/migrate/20210220145749_change_clients_date_of_birth_to_date_type.rb
- db/migrate/20210220193025_add_unique_index_to_prevent_multiple_vouchers_per_client_per_period.rb
- db/schema.rb
- db/seeds.rb
- test/factories/swap_periods.rb
- test/factories/users.rb
- test/models/current_swap_period_test.rb
- test/models/intake_period_test.rb
- test/models/swap_period_test.rb
- test/models/voucher_test.rb
- test/system/clients_test.rb
- test/system/vouchers_test.rb
Tying the date select default values in the voucher form to the swap period start/end dates, as well as respecting the swap dates that are still "available".
This means if today is 2/20, and Swap runs from 2/18 through 2/22, we really can only issue a voucher for the 2 remaining nights!
> Voucher Form Dates

- scripts/create_pilot_users.rb
I'm sure this can be accomplished in a better way. Thanks.
> Pilot users

- app/models/availability.rb
- app/models/swap.rb
- test/factories/swaps.rb
- test/models/intake_period_test.rb
fixing failing test suite after intake period changes
> swap intake tests

- app/javascript/packs/intake_form.js
Some file formatting and keyword assignment for 'questionKeys.' I am not sure how we did not get an error w/o a variable keyword, but alas.
> adds keyword to questionKeys variable

- app/controllers/admin/base_controller.rb
- app/controllers/clients_controller.rb
- app/controllers/hotels/base_controller.rb
- app/views/hotels/home/index.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- config/routes.rb
- db/migrate/20210326000739_add_intake_user_flag_to_users.rb
- db/schema.rb
- test/factories/users.rb
I just added the check for hotel_user in the client controller, putting it on both methods just in case. Seems to work.
> Hotel vouchers 2

- app/views/intakes/_form.html.erb
> Revert "explicitly run html5 check validity and submit form"

- test/factories/availabilities.rb
- test/factories/swaps.rb
dev QOL improvement..
```
rails c
factory_bot
create(:swap) 
```
> swaps factory update

- app/javascript/components/SwapWizard/Step1.js
- app/javascript/components/SwapWizard/Step3.js
- app/javascript/components/SwapWizard/Step4.js
- app/javascript/components/SwapWizard/Step5.js
remove extraneous <IntakeDate /> component
> refactor step5

- app/views/clients/index.html.erb
This reverts commit f09ed578daa40357dfc9d297262df73853eb2e98.
> Revert "temporarily bypass voucher requirement for intake button"

- Gemfile
- Gemfile.lock
- app/controllers/concerns/soft_deletable.rb
- app/helpers/hotels_helper.rb
- app/models/hotel.rb
- db/migrate/20211123040335_remove_logidze_from_hotels.rb
- db/migrate/20211123040336_convert_hotels_address_to_jsonb.rb
- db/migrate/20211123040702_readd_logidze_to_hotels.rb
- db/migrate/20211123040844_add_deleted_at_to_hotels.rb
- db/schema.rb
- test/factories/hotels.rb
- test/models/hotel_test.rb
jsonb column type. all to support soft delete
> soft delete

- Gemfile
- Gemfile.lock
- app/controllers/vouchers_controller.rb
- app/models/room_supply.rb
- app/models/voucher.rb
- app/views/vouchers/_form.html.erb
- test/commands/vouchers/void_test.rb
- test/controllers/vouchers_controller_test.rb
- test/models/extending_swap_test.rb
- test/models/room_supply_test.rb
- test/models/voucher_guests_test.rb
- test/models/voucher_test.rb
- test/test_helper.rb
> Prevent over-issuing

- app/controllers/clients_controller.rb
- app/controllers/intakes_controller.rb
- app/helpers/clients_helper.rb
- app/javascript/components/EditableProfilePhoto.js
- app/views/clients/_client_details.html.erb
- app/views/clients/_client_details_form.html.erb
- app/views/intakes/new.html.erb
- app/views/vouchers/_voucher.html.erb
- package.json
- yarn.lock
Wrap client profile display/editing functionality in component for isolation/re-use. React component `<EditableProfilePhoto />` is now rendered on all pages where clients appear in detail. Hotel users can also view saved client photo.
> Client details form improvements

- app/controllers/admin/reports_controller.rb
Make AH's vouchering process easier by including some last known location data
> add client last location to voucher report

- app/controllers/intakes_controller.rb
- app/javascript/components/EditableProfilePhoto.js
- app/javascript/components/UnshelteredHomelessnessVerification.js
- app/models/intake.rb
- app/views/intakes/new.html.erb
- db/migrate/20230430201051_add_hmis_id_to_clients.rb
- db/schema.rb
- test/factories/clients.rb
- test/system/intakes_test.rb
- test/test_helper.rb
Closes #252
* Store HMIS Identifiers on new client intake, and 
* Fixes new intake submission system test.
* Minor upgrades to system test runner in general with some Capybara configuration.
> HMIS Identifiers

- app/controllers/clients_controller.rb
- app/models/intake.rb
- app/views/clients/_client_details.html.erb
- app/views/clients/_client_details_form.html.erb
- app/views/clients/show.html.erb
- app/views/intakes/new.html.erb
- test/system/client_page_smoke_test.rb
- test/system/vouchers_test.rb
- layout client details similarly to new client intake form
- update hmis_id from client details edit form
- smoke test for client page
- disable failing vouchers test
- keep profile photo label when editing client details
> hmis id display and edit

- .devcontainer/Dockerfile
- .devcontainer/boot.sh
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
include .devcontainer folder with docker/compose config
> Codespaces Configuration

- app/controllers/vouchers_controller.rb
Allow users to see the street address of the hotel they are selecting on the voucher page.
@JacobValore
> Add hotel addresses to dropdown selections
